"use client";

import Link from "next/link";
import { FormEvent, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Brand } from "@/components/Header";

function strength(password: string) { const tests=[password.length>=8,/[A-Z]/.test(password),/[a-z]/.test(password),/[0-9]/.test(password),/[^A-Za-z0-9]/.test(password)].filter(Boolean).length; return tests <=2 ? "weak" : tests <=4 ? "medium" : "strong"; }
export default function RegisterPage() {
  const router=useRouter(); const [form,setForm]=useState({name:"",email:"",phone:"",password:"",confirm:""}); const [error,setError]=useState(""); const [loading,setLoading]=useState(false); const level=useMemo(()=>strength(form.password),[form.password]);
  const submit=async(event:FormEvent)=>{event.preventDefault();setError("");if(form.password!==form.confirm){setError("Passwords do not match.");return;}setLoading(true);try{const response=await fetch("/api/auth/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const data=await response.json();if(!response.ok){setError(data.error||"Unable to create account.");return;}router.push("/dashboard");router.refresh();}catch{setError("Network error. Please try again.");}finally{setLoading(false);}};
  const set=(key:keyof typeof form)=>(value:string)=>setForm(current=>({...current,[key]:value}));
  return <main className="auth-layout"><form className="auth-card" onSubmit={submit}><Brand/><h1 style={{fontSize:30}}>Create your account</h1><p className="muted">Citizen accounts can report and track civic issues.</p>{error&&<div className="alert error">{error}</div>}<div className="field"><label>Full name</label><input autoComplete="name" value={form.name} onChange={e=>set("name")(e.target.value)} required/></div><div className="field-row"><div className="field"><label>Email</label><input type="email" autoComplete="email" value={form.email} onChange={e=>set("email")(e.target.value)} required/></div><div className="field"><label>Phone number</label><input type="tel" autoComplete="tel" value={form.phone} onChange={e=>set("phone")(e.target.value)} required/></div></div><div className="field"><label>Password</label><input type="password" autoComplete="new-password" value={form.password} onChange={e=>set("password")(e.target.value)} required/><div className={`strength ${level}`}><span/><span/><span/></div><div className="strength-label">{form.password ? level[0].toUpperCase()+level.slice(1) : "Use 8+ characters with uppercase, lowercase, number and special character."}</div></div><div className="field"><label>Confirm password</label><input type="password" autoComplete="new-password" value={form.confirm} onChange={e=>set("confirm")(e.target.value)} required/></div><button className="button" style={{width:"100%"}} disabled={loading}>{loading?"Creating account…":"Create account"}</button><p className="auth-links">Already registered? <Link href="/login">Sign in</Link></p></form></main>;
}
