"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import ImageUpload, { CompressedImage } from "@/components/ImageUpload";
import { getCategory, formatDate, STATUS_LABELS } from "@/lib/civic";

type Item={ticketId:string;category:string;description:string;locationText:string;createdAt:string;severity:string;status:string;images:{dataUrl:string}[]};
export default function StaffComplaintCard({ complaint, assigned }: { complaint:Item; assigned:boolean }) { const router=useRouter();const [note,setNote]=useState("");const [image,setImage]=useState<CompressedImage|null>(null);const [completing,setCompleting]=useState(false);const [error,setError]=useState("");const [loading,setLoading]=useState(false);const action=async(action:"ACCEPT"|"START"|"COMPLETE", event?:FormEvent)=>{event?.preventDefault();setError("");if(action==="COMPLETE"&&(!image||note.trim().length<5)){setError("Add a completion note and photograph.");return;}setLoading(true);try{const r=await fetch(`/api/complaints/${complaint.ticketId}/status`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,note,imageData:image?.dataUrl,imageName:image?.name})});const d=await r.json();if(!r.ok){setError(d.error||"Unable to update complaint.");return;}router.refresh();setCompleting(false);}catch{setError("Network error. Please try again.");}finally{setLoading(false);}};const initial=complaint.images[0]?.dataUrl;return <article className="complaint-card">{initial?<img src={initial} alt="Reported issue"/>:<div className="issue-image"/>}<div><LinkText ticketId={complaint.ticketId}/><h3>{getCategory(complaint.category)?.label||complaint.category}</h3><p className="small-text">{complaint.description}</p><p className="small-text muted">{complaint.locationText} · Reported {formatDate(complaint.createdAt)} · {complaint.severity}</p>{error&&<div className="alert error">{error}</div>}{completing&&<form onSubmit={e=>void action("COMPLETE",e)} style={{marginTop:12}}><div className="field"><label>Completion note</label><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Describe the repair or action completed."/></div><div className="field"><label>Completion photograph</label><ImageUpload value={image} onChange={setImage}/></div><button className="button" disabled={loading}>{loading?"Completing…":"Confirm completion"}</button> <button className="button quiet" type="button" onClick={()=>setCompleting(false)}>Cancel</button></form>}</div><div><span className={`badge ${complaint.status}`}>{STATUS_LABELS[complaint.status]}</span>{!assigned&&<button className="button small" style={{marginTop:12}} disabled={loading} onClick={()=>void action("ACCEPT")}>{loading?"Accepting…":"Accept Complaint"}</button>}{assigned&&complaint.status==="ACCEPTED"&&<button className="button small" style={{marginTop:12}} disabled={loading} onClick={()=>void action("START")}>{loading?"Updating…":"Start Work"}</button>}{assigned&&complaint.status==="IN_PROGRESS"&&!completing&&<button className="button small" style={{marginTop:12}} onClick={()=>setCompleting(true)}>Complete Complaint</button>}</div></article>; }
function LinkText({ticketId}:{ticketId:string}){return <a className="ticket" href={`/track/${ticketId}`}>{ticketId}</a>;}
